name: Deploy bot

on:
  push:
    branches: ["master", "main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "dv-blackouts-bot"
  cancel-in-progress: true

env:
  CURRENT_DIR: /srv/dv-blackouts-bot/current
  RELEASES_DIR: /srv/dv-blackouts-bot/release

jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Copy result
        run: |
          mkdir "$RELEASES_DIR/$GITHUB_RUN_NUMBER"
          rsync -atl --exclude=.git/ --exclude=.gitignore --exclude=.github/ "./" "$RELEASES_DIR/$GITHUB_RUN_NUMBER"
      - name: Writing env file
        env:
          SUPER_SECRET: ${{ secrets.DOTENV }}
        run: |
          echo "$SUPER_SECRET" | base64 -d > $RELEASES_DIR/$GITHUB_RUN_NUMBER/.env
      - name: Stopping services
        run: |
          sudo service dv-blackouts-bot stop
      - name: Switch symlink
        run: |
          rm -Rf ${CURRENT_DIR}
          ln -s "$RELEASES_DIR/$GITHUB_RUN_NUMBER" ${CURRENT_DIR}
      - name: Starting services
        run: |
          sudo systemctl daemon-reload
          sudo service dv-blackouts-bot start
